baseurl = "https://speaker-candles-66888.netlify.com"
theme = "cocoa-eh-hugo-theme"
builddrafts = true
canonifyurls = true
contentdir = "content"
languageCode = "en-US"
layoutdir = "layouts"
publishdir = "public"
author = "Taavi Päll"
title = "Working on my analysis development skills"
disqusshortname = "www-credibleinterval-ee"
pluralizelisttitles = false

[permalinks]
blog = "blog/:slug/"

[params]
dateform = "Jan 2, 2006"
dateformfull = "Mon Jan 2 2006 15:04:05 MST"
description = "Digging in molecular biomedicine data"
copyright = "Copyright © 2017 Taavi Päll"
logofile = "img/face.jpg"
faviconfile = "img/face.jpg"
highlightjs = true
progressively = true
latestpostcount = 5
github = "tpall"
email = "tapa741@gmail.com"
linkedin = "palltaavi"
twitter = "taavipall"
social_banner = "img/tp-logo.png"
posts_navigation = true

[params.colors]
identifier = "#527fc1f"
identifier_dark = "#1a3152"
trivial = "#6a7a8b"
foreground = "#181d2a"
background = "#f9f9f9"
background_dark = "#282a36"
code = "#87a5d2"
type = "#97d28b"
special = "#ffcb8d"
value = "#96c2d7"
statement = "#ff8e91"
